CAR_MODELS_BY_BRANDS = {'Audi': ['100', '80', 'A3', 'A4', 'A4 Allroad Quattro', 'A5', 'A6', 'A6 Allroad Quattro', 'A7',
                                 'A8', 'Cabriolet', 'Coupe', 'Q2', 'Q3', 'Q5', 'Q5 Sportback', 'Q5 e-tron', 'Q5L', 'Q6',
                                 'Q7', 'Q8', 'Quattro', 'R8', 'RS Q3', 'RS Q3 Sportback', 'RS Q8', 'RS e-tron GT',
                                 'RS4', 'RS6', 'RS7', 'S4', 'S6', 'S8', 'TT'],
'BMW': ['02 (E10)', '1 серия', '1M', '2 серия', '2 серия Active Tourer', '2 серия Gran Coupe',
                                '2 серия Gran Tourer', '2000 C/CS', '3 серия', '3 серия GT', '321', '326', '327', '340',
                                '4 серия', '4 серия Gran Coupe', '5 серия', '5 серия GT', '503', '6 серия',
                                '6 серия GT', '6 серия Gran Coupe', '600', '7 серия', '8 серия', '8 серия Gran Coupe',
                                'E3', 'E9', 'M2', 'M3', 'M4', 'M5', 'M6', 'M8', 'M8 серия Gran Coupe', 'X1', 'X2', 'X3',
                                'X3 M', 'X4', 'X4 M', 'X5', 'X5 M', 'X6', 'X6 M', 'X7', 'XM', 'Z1', 'Z3', 'Z3 M', 'Z4',
                                'Z4 M', 'Z8', 'i3', 'i4', 'i7', 'i8', 'iX', 'iX1', 'iX3'],
                        'AC': ['378 GT Zagato', 'Ace', 'Aceca', 'Cobra'], 'AITO': ['M5', 'M7'],
                        'AM General': ['HMMWV (Humvee)'],
                        'AMC': ['Eagle', 'Hornet'],
                        'Acura': ['CL', 'CSX', 'EL', 'ILX', 'Integra', 'MDX', 'NSX', 'RDX', 'RL', 'RSX', 'SLX', 'TL',
                                  'TLX', 'TSX', 'ZDX'], 'Adler': ['Diplomat', 'Trumpf Junior'],
                        'Alfa Romeo': ['145', '146', '147', '155', '156', '159', '164', '166', '33', '4C', '6', '6C',
                                       '75', 'Brera', 'GT', 'GTV', 'Giulia', 'Giulietta', 'MiTo', 'SZ', 'Spider',
                                       'Sprint', 'Stelvio', 'Tonale'],
                        'Alpina': ['B10', 'B12', 'B3', 'B5', 'B6', 'B7', 'B8', 'D10', 'D3', 'D4', 'D5', 'Roadster',
                                   'XB7', 'XD3', 'XD4'], 'Alpine': ['A110', 'A310', 'A610', 'GTA'],
                        'Amico': ['Asena 224M'], 'Amphicar': ['770'], 'Arcfox': ['Alpha-S', 'Alpha-T'],
                        'Ariel': ['Atom'], 'Aro': ['10', '24'], 'Asia': ['Hi-topic', 'Rocsta', 'Towner'],
                        'Aston Martin': ['DB11', 'DB7', 'DB9', 'DBS', 'DBX', 'One-77', 'Rapide', 'Rapide S',
                                         'V8 Vantage', 'Vanquish', 'Virage'], 'Auburn': ['Speedster'],
                        'Aurus': ['Komendant', 'Senat'],
                        'Austin': ['FX4', 'Mini', 'Montego'], 'Austin Healey': ['100', '3000'], 'Autobianchi': ['A112'],
                        'Avatr': ['11'],
                        'BAIC': ['A1', 'BJ2020', 'BJ212', 'BJ40', 'BJ40 Plus', 'EU260', 'EU5', 'EU7', 'Luba (XB624)',
                                 'Ruixiang X5', 'U5 Plus', 'X35'], 'BAW': ['007', 'Fenix', 'Land King', 'Tonik'],
                        'BYD': ['Destroyer 05', 'Dolphin', 'E2', 'E6', 'F0', 'F3', 'F6', 'Flyer', 'Frigate 07',
                                'Han DM', 'Han EV', 'Qin Plus', 'Qin Pro', 'S6', 'Seal', 'Song EV', 'Song Plus',
                                'Song Pro', 'Tang EV', 'Yuan', 'Yuan Plus'], 'Bajaj': ['Qute'],
                        'Baltijas Dzips': ['BD-1322'], 'Baojun': ['360', 'E100', 'E200', 'E300'], 'Barkas': ['B1000'],
                        'Bentley': ['Arnage', 'Azure', 'Bentayga', 'Brooklands', 'Continental',
                                    'Continental Flying Spur', 'Continental GT', 'Eight', 'Flying Spur', 'Mulsanne',
                                    'S', 'Turbo R'], 'Bertone': ['Freeclimber'], 'Bilenkin': ['Vintage'],
                        'Bio Auto': ['evA-4'], 'Bitter': ['CD', 'Type 3'], 'Blaval': ['FH-EQ'],
                        'Borgward': ['2000', 'Hansa 1100'],
                        'Brilliance': ['H230', 'H530', 'M1 (BS6)', 'M2 (BS4)', 'V3', 'V5'],
                        'Bristol': ['Blenheim', 'Blenheim Speedster', 'Fighter'], 'Bufori': ['Geneva', 'La Joya'],
                        'Bugatti': ['Chiron', 'Veyron'],
                        'Buick': ['Cascada', 'Century', 'Electra', 'Enclave', 'Encore', 'Encore GX', 'Envision',
                                  'Excelle', 'GL8', 'LaCrosse', 'LeSabre', 'Park Avenue', 'Regal', 'Rendezvous',
                                  'Riviera', 'Roadmaster', 'Skylark', 'Special', 'Velite 6', 'Wildcat'],
                        'Cadillac': ['ATS', 'BLS', 'Brougham', 'CT4', 'CT5', 'CT6', 'CTS', 'CTS-V', 'Catera',
                                     'DE Ville', 'DTS', 'ELR', 'Eldorado', 'Escalade', 'Fleetwood', 'Lyriq', 'SRX',
                                     'STS', 'Seville', 'XLR', 'XT4', 'XT5', 'XT6', 'XTS'], 'Callaway': ['C12'],
                        'Caterham': ['21', '7'], 'ChangFeng': ['Flying PickUp', 'Liebao Leopard', 'SUV'],
                        'Changan': ['Alsvin', 'Auchan X5', 'Auchan X7', 'Auchan X7 EV', 'Benben E-Star', 'Benni',
                                    'Benni EV', 'CM-8', 'CS15', 'CS35', 'CS35 Plus', 'CS55', 'CS55 Plus', 'CS75',
                                    'CS75 Plus', 'CS85', 'CS95', 'Eado', 'Eado EV', 'Eado Plus', 'Kaicene F70',
                                    'Kuayue F3', 'M80', 'Raeton', 'UNI-K', 'UNI-T', 'UNI-V'], 'Changhe': ['Ideal'],
                        'Chery': ['Amulet (A15)', 'Arrizo 5E', 'Arrizo 7', 'Arrizo 8', 'Bonus (A13)', 'Bonus 3 (E3)',
                                  'CrossEastar (B14)', 'E5', 'Eastar', 'Fora (A21)', 'IndiS (S18D)', 'Karry',
                                  'Kimo (A1)', 'M11 (A3)', 'Oriental Son (B11)', 'QQ6 (S21)', 'Sweet (QQ)',
                                  'Tiggo (T11)', 'Tiggo 2', 'Tiggo 2 Pro', 'Tiggo 3', 'Tiggo 3x', 'Tiggo 3xe',
                                  'Tiggo 4', 'Tiggo 4 Pro', 'Tiggo 5', 'Tiggo 7', 'Tiggo 7 Pro', 'Tiggo 7 Pro Max',
                                  'Tiggo 8', 'Tiggo 8 Pro', 'Tiggo 8 Pro (China)', 'Tiggo 8 Pro Max', 'Tiggo 8 Pro e+',
                                  'Tiggo E', 'Very', 'eQ1', 'eQ5'], 'CheryExeed': ['TXL'],
                        'Chevrolet': ['3000 Series', 'Alero', 'Astra', 'Astro', 'Avalanche', 'Aveo', 'Bel Air',
                                      'Beretta', 'Blazer', 'Blazer K5', 'Bolt', 'C/K', 'Camaro', 'Caprice', 'Captiva',
                                      'Cavalier', 'Celebrity', 'Chevelle', 'Chevette', 'Cobalt', 'Colorado', 'Corsica',
                                      'Corvair', 'Corvette', 'Cruze', 'Cruze HR', 'Damas', 'Deluxe', 'El Camino',
                                      'Epica', 'Equinox', 'Evanda', 'Express', 'Groove', 'HHR', 'Impala', 'Lacetti',
                                      'Lanos', 'Lumina', 'Lumina APV', 'MW', 'Malibu', 'Matiz', 'Menlo', 'Metro',
                                      'Monte Carlo', 'Monza', 'Nexia', 'Niva', 'Nova', 'Nubira', 'Onix', 'Optra',
                                      'Orlando', 'Prizm', 'Rezzo', 'S10', 'SSR', 'Silverado', 'Sonic', 'Spark',
                                      'Sprint', 'Starcraft', 'Suburban', 'Tahoe', 'Tracker', 'TrailBlazer',
                                      'Trans Sport', 'Traverse', 'Trax', 'Uplander', 'Van', 'Venture', 'Viva', 'Volt'],
                        'Chrysler': ['180', '200', '300 Letter Series', '300C', '300M', '70 Six', 'Cirrus', 'Concorde',
                                     'Cordoba', 'Crossfire', 'Dynasty', 'Fifth Avenue', 'Grand Voyager', 'Intrepid',
                                     'LHS', 'LeBaron', 'Neon', 'New Yorker', 'PT Cruiser', 'Pacifica', 'Prowler',
                                     'Saratoga', 'Sebring', 'Simca 1308 GT', 'Stratus', 'Town & Country', 'Vision',
                                     'Voyager'],
                        'Citroen': ['AX', 'BX', 'Berlingo', 'C-Crosser', 'C-Elysee', 'C1', 'C15', 'C2', 'C25', 'C3',
                                    'C3 Aircross', 'C3 Picasso', 'C4', 'C4 Aircross'], 'Cizeta': ['V16T'],
                        'Coggiola': ['T-Rex'], 'Cord': ['L-29'], 'Cupra': ['Ateca', 'Born', 'Formentor', 'Leon'],
                        'DKW': ['3=6'],
                        'DS': ['DS 3', 'DS 3 Crossback', 'DS 4', 'DS 4 Crossback', 'DS 5', 'DS 7 Crossback'],
                        'DW Hower': ['H3', 'H5'],
                        'Dacia': ['1310', 'Dokker Stepway', 'Duster', 'Lodgy', 'Logan', 'Nova', 'Sandero', 'Solenza',
                                  'Super Nova'], 'Dadi': ['City Leading', 'Shuttle', 'Smoothing'],
                        'Daewoo': ['Alpheon', 'Charman', 'Damas', 'Espero', 'Evanda', 'G2X', 'Gentra', 'Kalos',
                                   'Lacetti', 'Lacetti Premiere', 'Lanos', 'LeMans', 'Leganza', 'Lublin', 'Magnus',
                                   'Matiz', 'Matiz Creative', 'Musso', 'Nexia', 'Nubira', 'Prince', 'Racer', 'Rezzo',
                                   'Sens', 'Tacuma', 'Tico', 'Tosca', 'Winstorm'],
                        'Daihatsu': ['Altis', 'Applause', 'Atrai', 'Be-go', 'Boon', 'Boon Luminas', 'Cast', 'Charade',
                                     'Charmant', 'Coo', 'Copen', 'Cuore', 'Delta', 'Esse', 'Feroza', 'Gran Max',
                                     'Gran Move', 'Hijet', 'Hijet Caddie', 'Hijet Truck', 'Leeza', 'MAX', 'Materia',
                                     'Mebius', 'Mira', 'Mira e:S', 'Move', 'Move Canbus', 'Move Conte', 'Naked', 'Opti',
                                     'Pyzar', 'Rocky', 'Sirion', 'Sonica', 'Storia', 'Taft', 'Tanto', 'Tanto Exe',
                                     'Terios', 'Terios Kid', 'Thor', 'Trevis', 'Wake', 'Wildcat', 'YRV'],
                        'Daimler': ['Limousine', 'Super Eight', 'X308', 'XJ'],
                        'Datsun': ['100A/120A', '1200', '120Y', '220C', '720', 'Sunny', 'Violet', 'mi-DO', 'on-DO'],
                        'De Tomaso': ['Bigua', 'Guara', 'Mangusta', 'Pantera', 'Vallelunga'], 'DeLorean': ['DMC-12'],
                        'DeSoto': ['Custom', 'Firedome', 'Fireflite'], 'Delage': ['D6'],
                        'Denza': ['D9', 'D9 EV', 'X', 'X EV'],
                        'Derways': ['Antelope', 'Aurora', 'Cowboy', 'Land Crown', 'Plutus', 'Saladin', 'Shuttle'],
                        'Dodge': ['Aries', 'Avenger', 'Caliber', 'Caravan', 'Challenger', 'Charger', 'Custom Royal',
                                  'D/W Series', 'Dakota', 'Dart', 'Daytona', 'Diplomat', 'Durango', 'Dynasty',
                                  'Grand Caravan', 'Intrepid', 'Journey', 'Magnum', 'Neon', 'Nitro', 'Ram',
                                  'Ram Promaster City', 'Ram Van', 'Shadow', 'Spirit', 'Stealth', 'Stratus', 'Viper',
                                  'WC series'],
                        'Dongfeng': ['580', 'AX7', 'DF6', 'E11K', 'EC35', 'Fengguang ix5', 'H30 Cross', 'Lingzhi M5',
                                     'Lingzhi M5EV', 'M-NV', 'MPV', 'Rich', 'S30', 'X-NV'],
                        'Doninvest': ['Assol', 'Kondor', 'Orion'], 'Donkervoort': ['D8', 'D8 GTO'], 'E-Car': ['GD04B'],
                        'EXEED': ['LX', 'TXL', 'VX', 'Yaoguang'], 'Eagle': ['Summit', 'Talon', 'Vision'],
                        'Eagle Cars': ['SS'], 'Evolute': ['i-JET', 'i-JOY', 'i-PRO', 'i-VAN'],
                        'Excalibur': ['Series IV', 'Series V'],
                        'FAW': ['6350', 'Bestune B70', 'Bestune NAT', 'Bestune T55', 'Bestune T77', 'Bestune T99',
                                'Besturn B50', 'Besturn B70', 'Besturn X40', 'Besturn X80', 'Jinn', 'Jumpal D60',
                                'Oley', 'V2', 'V5', 'Vita'],
                        'FIAT': ['124', '124 Spider', '124 Sport Spider', '125', '126', '127', '131', '500', '500L',
                                 '500X', 'Albea', 'Argenta', 'Barchetta', 'Brava', 'Bravo', 'Cinquecento', 'Coupe',
                                 'Croma', 'Doblo', 'Ducato', 'Duna', 'Fiorino', 'Freemont', 'Fullback', 'Idea', 'Linea',
                                 'Marea', 'Multipla', 'Palio', 'Panda', 'Punto', 'Qubo', 'Regata', 'Ritmo', 'Scudo',
                                 'Sedici', 'Seicento', 'Siena', 'Stilo', 'Strada', 'Talento', 'Tempra', 'Tipo',
                                 'Ulysse', 'Uno'], 'FSO': ['125p', '126p', '127p', '132p', 'Polonez'],
                        'Ferrari': ['296 GTB', '328', '348', '360', '456', '458 Italia', '458 Spider', '488 GTB',
                                    '488 Pista', '575M Maranello', '599 GTB Fiorano', '612 Scaglietti', '812 Superfast',
                                    'California', 'F12berlinetta', 'F355', 'F430', 'F8 Spider', 'F8 Tributo', 'FF',
                                    'GTC4Lusso', 'Mondial', 'Portofino', 'Purosangue', 'Roma', 'SF90 Stradale',
                                    'Testarossa'], 'Fisker': ['Karma'],
                        'Ford': ['Aerostar', 'Anglia', 'Aspire', 'B-MAX', 'Bronco', 'Bronco II', 'Bronco Sport',
                                 'C-MAX', 'Capri', 'Consul', 'Contour', 'Cougar', 'Country Squire', 'Courier',
                                 'Crown Victoria', 'Custom', 'Customline', 'EcoSport', 'Econoline', 'Econovan', 'Edge',
                                 'Escape', 'Escort', 'Escort (North America)', 'Excursion', 'Expedition', 'Explorer',
                                 'Explorer Sport Trac', 'F-150', 'F-250', 'F-350', 'Fairlane', 'Fairmont', 'Festiva',
                                 'Fiesta', 'Fiesta ST', 'Figo', 'Five Hundred', 'Flex', 'Focus', 'Focus RS', 'Focus ST',
                                 'Freda', 'Freestyle', 'Fusion', 'Fusion (North America)', 'GT', 'Galaxie', 'Galaxy',
                                 'Granada', 'Grand C-MAX', 'Ixion', 'Ka', 'Kuga', 'LTD Crown Victoria', 'Laser',
                                 'Maverick', 'Model A', 'Model B', 'Model T', 'Mondeo', 'Mondeo ST', 'Mustang',
                                 'Mustang Mach-E', 'Orion', 'P100', 'Probe', 'Puma', 'Ranchero', 'Ranger',
                                 'Ranger (North America)', 'S-MAX', 'Scorpio', 'Sierra', 'Spectron', 'Taunus', 'Taurus',
                                 'Telstar', 'Tempo', 'Territory EV', 'Thunderbird', 'Torino', 'Tourneo',
                                 'Tourneo Connect', 'Tourneo Courier', 'Tourneo Custom', 'Transit', 'Transit Connect',
                                 'Transit Custom', 'V8', 'Windstar'], 'Forthing': ['T5 EVO', 'Yacht'],
                        'Foton': ['Alpha Van', 'Sauvana', 'Tunland', 'View CS2'], 'Fuqi': ['6500 Land King'],
                        'GAC': ['Aion LX', 'Aion S', 'Aion V', 'Aion Y', 'GE3', 'GN8', 'GS5', 'GS8', 'WAY M1', 'WAY M2',
                                'WAY V1', 'iA5'],
                        'GMC': ['Acadia', 'Envoy', 'Hummer EV', 'Jimmy', 'Safari', 'Savana', 'Sierra', 'Sonoma',
                                'Suburban', 'Terrain', 'Typhoon', 'Vandura', 'Yukon'], 'GP': ['Madison'],
                        'Geely': ['Atlas', 'Atlas Pro', 'Binyue Cool', 'CK (Otaka)', 'Coolray', 'Emgrand 7',
                                  'Emgrand EC7', 'Emgrand EC8', 'Emgrand EV', 'Emgrand GT', 'Emgrand X7', 'FC (Vision)',
                                  'GC6', 'GS', 'Geometry A', 'Geometry C', 'Icon', 'Jiaji', 'LC (GC2)', 'MK',
                                  'MK Cross', 'Maple SL', 'Monjaro', 'Okavango', 'Preface', 'SC7', 'Tugella',
                                  'Vision X3 Pro'], 'Genesis': ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80'],
                        'Geo': ['Metro', 'Prizm', 'Storm', 'Tracker'], 'Golden Dragon': ['MPV'], 'Gonow': ['Troy'],
                        'Gordon': ['Roadster'], 'Graham-Paige': ['610', '97'],
                        'Great Wall': ['Coolbear', 'Cowry', 'Deer', 'Florid', 'Hover', 'Hover H3', 'Hover H5',
                                       'Hover H6', 'Hover M2', 'Hover M4', 'Pegasus', 'Peri', 'Poer', 'Poer Kingkong',
                                       'Safe', 'Sailor', 'Sing RUV', 'Sokol', 'Voleex C30', 'Wingle', 'Wingle 7'],
                        'Groz': ['Polarsun'], 'HSV': ['ClubSport R8'], 'Hafei': ['Brio', 'Princip', 'Simbo'],
                        'Haima': ['3', '7', 'M3'], 'Hanomag': ['Rekord'], 'Hanteng': ['X5', 'X7'],
                        'Haval': ['Chitu', 'DaGou (Big Dog)', 'Dargo', 'Dargo X', 'F5', 'F7', 'F7x', 'H2', 'H5', 'H6',
                                  'H6 Coupe', 'H8', 'H9', 'Jolion', 'KuGou (Cool Dog)'],
                        'Hawtai': ['Boliger', 'Laville'], 'Heinkel': ['Kabine'], 'HiPhi': ['X', 'Z'],
                        'Hindustan': ['Ambassador', 'Contessa'], 'Hispano-Suiza': ['K6'], 'Hobbycar': ['B612'],
                        'Honda': ['Accord', 'Acty', 'Airwave', 'Ascot', 'Ascot Innova', 'Avancier', 'Ballade', 'Beat',
                                  'CR-V', 'CR-X', 'CR-Z', 'Capa', 'City', 'Civic', 'Civic Ferio', 'Clarity', 'Concerto',
                                  'Crider', 'Crossroad', 'Crosstour', 'Domani', 'Edix', 'Element', 'Elysion',
                                  'Everus VE-1', 'FR-V', 'Fit', 'Fit Aria', 'Fit Shuttle', 'Freed', 'Freed+', 'Grace',
                                  'HR-V', 'Insight', 'Inspire', 'Integra', 'Integra SJ', 'Jade', 'Jazz', 'Jazz AA',
                                  'Legend', 'Life', 'Logo', 'M-NV', 'MDX', 'Mobilio', 'Mobilio Spike', 'N-BOX', 'N-One',
                                  'N-VAN', 'N-WGN', 'NSX', 'Odyssey', 'Odyssey (North America)', 'Orthia', 'Partner',
                                  'Passport', 'Pilot', 'Prelude', 'Rafaga', 'Ridgeline', 'S-MX', 'S2000', 'S660',
                                  'Saber', 'Shuttle', 'Stepwgn', 'Stream', 'Street', 'That S', 'Today', 'Torneo',
                                  'UR-V', 'Vamos', 'Vezel', 'Vigor', 'X-NV', 'XR-V', 'Z', 'ZR-V', 'Zest', 'e', 'e:NP1',
                                  'e:NS1'],
                        'Hongqi': ['E-HS3', 'E-HS9', 'E-QM5', 'H5', 'H7', 'H9', 'HQ9', 'HS5', 'HS7'],
                        'Horch': ['830', '853'], 'Huanghai': ['Antelope', 'Landscape'], 'Hudson': ['Deluxe Eight'],
                        'Hummer': ['H1', 'H2', 'H3', 'HMWV М-998'],
                        'Hyundai': ['Accent', 'Atos', 'Avante', 'Azera', 'Bayon', 'Casper', 'Celesta', 'Centennial',
                                    'Click', 'Coupe', 'Creta', 'Custo', 'Dynasty', 'Elantra', 'Encino', 'Equus',
                                    'Excel', 'Galloper', 'Genesis', 'Getz', 'Grace', 'Grand Creta', 'Grand Santa Fe',
                                    'Grand Starex', 'Grandeur', 'H-1', 'H-100', 'H-200', 'IONIQ', 'IONIQ 5', 'IONIQ 6',
                                    'Kona', 'Lafesta', 'Lantra', 'Lavita', 'Marcia', 'Matrix', 'Maxcruz', 'Palisade',
                                    'Pony', 'Porter', 'S-Coupe', 'Santa Cruz', 'Santa Fe', 'Santamo', 'Solaris',
                                    'Sonata', 'Starex', 'Staria', 'Stellar', 'Terracan', 'Tiburon', 'Trajet', 'Tucson',
                                    'Tuscani', 'Veloster', 'Venue', 'Veracruz', 'Verna', 'XG', 'i10', 'i20', 'i30',
                                    'i30 N', 'i40', 'ix20', 'ix35', 'ix55'], 'Imperial': ['LeBaron'],
                        'Infiniti': ['EX25', 'EX30', 'EX35', 'EX37', 'FX30', 'FX35', 'FX37', 'FX45', 'FX50', 'G20',
                                     'G25', 'G35', 'G37', 'I30', 'I35', 'J30', 'JX', 'M25', 'M35', 'M37', 'M45', 'M56',
                                     'Q30', 'Q45', 'Q50', 'Q60', 'Q70', 'QX30', 'QX4', 'QX50', 'QX55', 'QX56', 'QX60',
                                     'QX70', 'QX80'], 'Innocenti': ['Elba', 'Mille', 'Mini'], 'Invicta': ['S1'],
                        'Iran Khodro': ['Dena', 'Runna', 'Sahra', 'Samand', 'Soren', 'Tara'],
                        'Isdera': ['Imperator 108i', 'Spyder'],
                        'Isuzu': ['Amigo', 'Aska', 'Axiom', 'Bighorn', 'Campo', 'D-Max', 'Fargo', 'Filly', 'Gemini',
                                  'Impulse', 'MU', 'MU-X', 'Midi', 'Oasis', 'Piazza', 'Pickup (QL1032)', 'Rodeo', 'T17',
                                  'Trooper', 'VehiCross', 'Wizard'], 'Iveco': ['Daily', 'Massif'],
                        'JAC': ['J2', 'J5', 'J7', 'JS4', 'JS6', 'Refine', 'Rein', 'S3', 'S4', 'S5', 'S7', 'T6',
                                'T8 Pro', 'iEV6', 'iEV7S', 'iEVA50', 'iEVS4'], 'JMC': ['1032', '1052', 'Baodian'],
                        'Jaguar': ['E-Pace', 'E-type', 'F-Pace', 'F-type', 'I-Pace', 'Mark 2', 'Mark IX', 'S-type',
                                   'X-type', 'XE', 'XF', 'XFR', 'XJ', 'XJR', 'XJS', 'XK', 'XKR'],
                        'Jeep': ['CJ', 'Cherokee', 'Commander', 'Compass', 'Gladiator', 'Grand Cherokee', 'Liberty',
                                 'Patriot', 'Renegade', 'Wagoneer', 'Wrangler'], 'Jensen': ['Interceptor', 'S-V8'],
                        'Jetour': ['Dashing', 'X70', 'X70 EV', 'X70 Plus', 'X70S', 'X90', 'X90 Plus', 'X95'],
                        'Jetta': ['VA3', 'VS5', 'VS7'], 'Jinbei': ['Haise'], 'Jonway': ['UFO'], 'KTM': ['X-Bow'],
                        'KYC': ['V3'], 'Kaiyi': ['E5', 'X3', 'X3 pro'], 'Khazar': ['SD'],
                        'Kia': ['Avella', 'Besta', 'Bongo', 'Cadenza', 'Capital', 'Carens', 'Carnival', 'Ceed',
                                'Ceed GT', 'Cerato', 'Clarus', 'Concord', 'EV6', 'Enterprise', 'Forte', 'Joice', 'K3',
                                'K5', 'K7', 'K8', 'K9', 'K900', 'KX1', 'KX3', 'Lotze', 'Magentis', 'Mentor', 'Mohave',
                                'Morning', 'Niro', 'Opirus', 'Optima', 'Pegas', 'Picanto', 'Picanto X-Line', 'Potentia',
                                'Pregio', 'Pride', 'ProCeed', 'Quoris', 'Ray', 'Retona', 'Rio', 'Rio X', 'Rio X-Line',
                                'Sedona', 'Seltos', 'Sephia', 'Shuma', 'Sonet', 'Sorento', 'Sorento Prime', 'Soul',
                                'Spectra', 'Sportage', 'Sportage (China)', 'Stinger', 'Stonic', 'Telluride', 'Towner',
                                'Venga', 'Visto', 'X-Trek', 'XCeed'],
                        'Koenigsegg': ['Agera', 'CC8S', 'CCR', 'CCX', 'One:1', 'Regera'], 'LDV': ['Convoy', 'Maxus'],
                        'LIFAN': ['Breez (520)', 'Cebrium (720)', 'Celliya (530)', 'Murman', 'Myway', 'Smily (320)',
                                  'Solano', 'X50', 'X60', 'X70'], 'LTI': ['TX1', 'TX4', 'TXII'],
                        'Lamborghini': ['Aventador', 'Countach', 'Diablo', 'Gallardo', 'Huracan', 'LM002', 'Miura',
                                        'Murcielago', 'Urus'],
                        'Lancia': ['Dedra', 'Delta', 'Kappa', 'Lybra', 'Musa', 'Phedra', 'Prisma', 'Thema', 'Thesis',
                                   'Trevi', 'Voyager', 'Ypsilon', 'Zeta'],
                        'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Freelander', 'Range Rover',
                                       'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar', 'Series III'],
                        'Landwind': ['Fashion', 'X6'], 'Leapmotor': ['C01', 'C11', 'T03'],
                        'Lexus': ['CT', 'ES', 'GS', 'GS F', 'GX', 'HS', 'IS', 'IS F', 'LC', 'LFA', 'LM', 'LS', 'LX',
                                  'NX', 'RC', 'RC F', 'RX', 'RZ', 'SC', 'UX'], 'Leyland': ['Sherpa'],
                        'LiXiang': ['L7', 'L8', 'L9', 'One'], 'Lichi': ['A01'], 'Ligier': ['JS 51'],
                        'Lincoln': ['Aviator', 'Continental', 'Corsair', 'LS', 'MKC', 'MKS', 'MKT', 'MKX', 'MKZ',
                                    'Mark', 'Mark LT', 'Mark VII', 'Mark VIII', 'Nautilus', 'Navigator', 'Town Car',
                                    'Zephyr'], 'Livan': ['X3 pro'],
                        'Lotus': ['Eletre', 'Elise', 'Esprit', 'Europa S', 'Evora', 'Exige'], 'Lucid': ['Air'],
                        'Luxgen': ['7 MPV', '7 SUV', 'U7 Turbo'], 'Lynk & Co': ['01', '05', '06', '09'],
                        'MG': ['3 Cross', '350', '550', '6', 'F', 'HS', 'MGB', 'Mulan', 'TF', 'ZR', 'ZS', 'ZT'],
                        'MINI': ['Cooper', 'Cooper Clubman', 'Cooper Countryman', 'Cooper Paceman', 'Cooper S',
                                 'Cooper S Clubman', 'Cooper S Countryman', 'Cooper S Paceman', 'Cooper SD Clubman',
                                 'Cooper SD Countryman', 'Cooper SE', 'Cooper SE Countryman', 'John Cooper Works',
                                 'John Cooper Works Clubman', 'John Cooper Works Countryman',
                                 'John Cooper Works Paceman', 'One'], 'Mahindra': ['Marshal'],
                        'Marcos': ['GTS', 'LM 400', 'LM 500', 'Marcasite'], 'Marlin': ['5EXi', 'Sportster'],
                        'Marussia': ['B1', 'B2', 'F2'],
                        'Maruti': ['1000', '800', 'Alto', 'Baleno', 'Esteem', 'Gypsy', 'Omni', 'Versa', 'Wagon R',
                                   'Zen'],
                        'Maserati': ['3200 GT', '4200 GT', 'Biturbo', 'Ghibli', 'GranTurismo', 'Grecale', 'Levante',
                                     'Quattroporte'], 'Maxus': ['D90 Pro', 'G50', 'G90'], 'Maybach': ['57', '62'],
                        'Mazda': ['1000', '121', '1300', '2', '3', '3 MPS', '323', '5', '6', '6 MPS', '616', '626',
                                  '818', '929', 'AZ-Offroad', 'AZ-Wagon', 'Atenza', 'Autozam AZ-1', 'Autozam AZ-3',
                                  'Axela', 'B-Series', 'BT-50', 'Biante', 'Bongo', 'Bongo Brawny', 'Bongo Friendee',
                                  'CX-3', 'CX-30', 'CX-4', 'CX-5', 'CX-50', 'CX-60', 'CX-7', 'CX-8', 'CX-9', 'CX-90',
                                  'Capella', 'Carol', 'Chantez', 'Cosmo', 'Cronos', 'Demio', 'Efini MS-6', 'Efini MS-8',
                                  'Efini MS-9', 'Etude', 'Eunos 100', 'Eunos 300', 'Eunos 500', 'Eunos 800',
                                  'Eunos Cosmo', 'Eunos Presso', 'Familia', 'Flair', 'Flair Crossover', 'Flair Wagon',
                                  'Lantis', 'Laputa', 'Levante', 'Luce', 'MPV', 'MX-3', 'MX-30', 'MX-5', 'MX-6',
                                  'Millenia', 'Navajo', 'Persona', 'Premacy', 'Proceed', 'Proceed Levante',
                                  'Proceed Marvie', 'Protege', 'R360', 'RX-7', 'RX-8', 'Revue', 'Roadster', 'Scrum',
                                  'Sentia', 'Spiano', 'Tribute', 'Verisa', 'Xedos 6', 'Xedos 9'],
                        'McLaren': ['540C', '570GT', '570S', '600LT', '650S', '675LT', '720S', '765LT', 'Artura', 'F1',
                                    'GT', 'MP4-12C', 'P1', 'Senna'], 'Mega': ['Club', 'Monte Carlo', 'Track'],
                        'Mercedes-Benz': ['190 (W201)', '190 SL', '220 (W187)', 'A-класс', 'A-класс AMG', 'AMG GT',
                                          'B-класс', 'C-класс', 'C-класс AMG', 'CL-класс', 'CL-класс AMG', 'CLA-класс',
                                          'CLA-класс AMG', 'CLC-класс', 'CLK-класс', 'CLK-класс AMG', 'CLS-класс',
                                          'CLS-класс AMG', 'Citan', 'E-класс', 'E-класс AMG', 'E-класс All-Terrain',
                                          'EQA', 'EQB', 'EQC', 'EQE', 'EQE AMG', 'EQS', 'EQS AMG', 'EQS SUV', 'EQV',
                                          'G-класс', 'G-класс AMG', 'GL-класс', 'GL-класс AMG', 'GLA-класс',
                                          'GLA-класс AMG', 'GLB-класс', 'GLB-класс AMG', 'GLC-класс', 'GLC-класс AMG',
                                          'GLC-класс AMG Coupe', 'GLC-класс Coupe', 'GLE-класс', 'GLE-класс AMG',
                                          'GLE-класс AMG Coupe', 'GLE-класс Coupe', 'GLK-класс', 'GLS-класс',
                                          'GLS-класс AMG', 'M-класс', 'M-класс AMG', 'MB100', 'Maybach GLS-класс',
                                          'Maybach S-класс', 'Metris', 'Pullman', 'R-класс', 'R-класс AMG', 'S-класс',
                                          'S-класс AMG', 'SL-класс', 'SL-класс AMG', 'SLC-класс', 'SLC-класс AMG',
                                          'SLK-класс', 'SLK-класс AMG', 'SLR McLaren', 'SLS-класс AMG', 'Simplex',
                                          'Sprinter', 'Sprinter Classic', 'T1', 'T2', 'V-класс', 'Vaneo', 'Vario',
                                          'Viano', 'Vito', 'W100', 'W105', 'W108', 'W110', 'W111', 'W114', 'W115',
                                          'W120', 'W123', 'W124', 'W128', 'W136', 'W180', 'W186', 'W188', 'W189', 'W29',
                                          'X-класс'],
                        'Mercury': ['Comet', 'Cougar', 'Grand Marquis', 'Mariner', 'Marquis', 'Milan', 'Montego',
                                    'Monterey', 'Mountaineer', 'Mystique', 'Sable', 'Topaz', 'Tracer', 'Villager'],
                        'Messerschmitt': ['KR200'], 'Metrocab': ['Taxi'],
                        'Microcar': ['F8C', 'M.Go', 'M8', 'MC', 'Virgo'], 'Minelli': ['TF 1800'],
                        'Mitsubishi': ['3000 GT', 'ASX', 'Airtrek', 'Aspire', 'Attrage', 'Carisma', 'Celeste',
                                       'Challenger', 'Chariot', 'Colt', 'Debonair', 'Delica', 'Delica D2', 'Delica D3',
                                       'Delica D5', 'Diamante', 'Dingo', 'Dion', 'EK Custom', 'EK Space', 'EK Sport',
                                       'EK Wagon', 'Eclipse', 'Eclipse Cross', 'Emeraude', 'Endeavor', 'Eterna', 'FTO',
                                       'GTO', 'Galant', 'Galant Fortis', 'Grandis', 'Jeep', 'L200', 'L300', 'L400',
                                       'Lancer', 'Lancer Cargo', 'Lancer Cedia', 'Lancer Evolution', 'Lancer Ralliart',
                                       'Legnum', 'Libero', 'Minica', 'Minicab', 'Minicab MiEV', 'Mirage', 'Montero',
                                       'Montero Sport', 'Outlander', 'Outlander Sport', 'Pajero', 'Pajero Junior',
                                       'Pajero Mini', 'Pajero Pinin', 'Pajero Sport', 'Pajero iO', 'RVR', 'Sapporo',
                                       'Sigma', 'Space Gear', 'Space Runner', 'Space Star', 'Space Wagon', 'Starion',
                                       'Strada', 'Toppo', 'Town BOX', 'Triton', 'Xpander', 'Xpander Cross', 'i',
                                       'i-MiEV'], 'Mitsuoka': ['Galue', 'Le-Seyde'], 'Morgan': ['Aero', 'Plus 4'],
                        'Morris': ['Marina'], 'NIO': ['ES6', 'ES7', 'ES8', 'ET5', 'ET7', 'EС6', 'EС7'],
                        'Nash': ['Ambassador'], 'Neta': ['U', 'V'],
                        'Nissan': ['100NX', '180SX', '200SX', '240SX', '280ZX', '300ZX', '350Z', '370Z', 'AD', 'Almera',
                                   'Almera Classic', 'Almera Tino', 'Altima', 'Ariya', 'Armada', 'Auster', 'Avenir',
                                   'Bassara', 'Bluebird', 'Bluebird Sylphy', 'Cabstar', 'Caravan', 'Cedric', 'Cefiro',
                                   'Cherry', 'Cima', 'Clipper', 'Crew', 'Cube', 'Datsun', 'Dayz', 'Dayz Roox', 'Dualis',
                                   'Elgrand', 'Expert', 'Fairlady', 'Figaro', 'Frontier', 'Fuga', 'GT-R', 'Gloria',
                                   'Homy', 'Interstar', 'Juke', 'Kicks', 'Kix', 'Kubistar', 'Lafesta', 'Langley',
                                   'Largo', 'Latio', 'Laurel', 'Leaf', 'Leopard', 'Liberta Villa', 'Liberty', 'Lucino',
                                   'March', 'Maxima', 'Micra', 'Mistral', 'Moco', 'Murano', 'NP300', 'NV100 Clipper',
                                   'NV200', 'NV300', 'NV350 Caravan', 'NV400', 'NX Coupe', 'Navara', 'Note', 'Otti',
                                   'Pathfinder', 'Patrol', 'Pick UP', 'Pino', 'Pixo', 'Prairie', 'Presage', 'Presea',
                                   'President', 'Primastar', 'Primera', 'Pulsar', 'Qashqai', 'Qashqai+2', 'Quest',
                                   'R Nessa', 'Rasheen', 'Rogue', 'Rogue Sport', 'Roox', 'S-Cargo', 'Safari', 'Sentra',
                                   'Serena', 'Silvia', 'Skyline', 'Stagea', 'Stanza', 'Sunny', 'Sunny California',
                                   'Sylphy Zero Emission', 'Teana', 'Terrano', 'Terrano II', 'Tiida', 'Tiida Latio',
                                   'Tino', 'Titan', 'Trade', 'Urvan', 'Vanette', 'Vanette Cargo', 'Versa', 'Violet',
                                   'Wingroad', 'X-Terra', 'X-Trail', 'Z', 'e-NV200'], 'Noble': ['M12', 'M15', 'M600'],
                        'Nysa': ['522'], 'OMODA': ['C5', 'S5'],
                        'Oldsmobile': ['Achieva', 'Alero', 'Aurora', 'Bravada', 'Cutlass', 'Cutlass Ciera',
                                       'Cutlass Supreme', 'Eighty-Eight', 'Ninety-Eight', 'Omega', 'Silhouette',
                                       'Toronado'],
                        'Opel': ['Adam', 'Adam Rocks', 'Admiral', 'Agila', 'Ampera', 'Antara', 'Arena', 'Ascona',
                                 'Astra', 'Astra Family', 'Astra GTC', 'Astra OPC', 'Bedford', 'Calibra', 'Campo',
                                 'Cascada', 'Combo', 'Combo Life', 'Commodore', 'Corsa', 'Corsa OPC', 'Crossland',
                                 'Crossland X', 'Diplomat', 'Frontera', 'GT', 'Grandland X', 'Insignia', 'Insignia OPC',
                                 'Kadett', 'Kapitan', 'Karl', 'Manta', 'Meriva', 'Meriva OPC', 'Mokka', 'Monterey',
                                 'Monza', 'Movano', 'Olympia', 'Omega', 'P4', 'Rekord', 'Senator', 'Signum', 'Sintra',
                                 'Super 6', 'Tigra', 'Vectra', 'Vectra OPC', 'Vita', 'Vivaro', 'Zafira', 'Zafira Life',
                                 'Zafira OPC'], 'Ora': ['Ballet Cat', 'Good Cat'], 'Osca': ['2500 GT'],
                        'Oshan': ['X5', 'X7', 'X7 Plus', 'Z6'], 'PGO': ['Cevennes', 'Hemera', 'Speedster II'],
                        'PUCH': ['G-modell', 'Pinzgauer'],
                        'Packard': ['200/250', 'Clipper', 'Custom Eight', 'One-Twenty', 'Twelve', 'Twin Six'],
                        'Pagani': ['Huayra', 'Zonda'], 'Panhard & Levassor': ['Type A'],
                        'Panoz': ['Esperante', 'Roadster'],
                        'Peugeot': ['1007', '104', '106', '107', '108', '2008', '203', '205', '206', '207', '208',
                                    '3008', '301', '305', '306', '307', '308', '309', '4007', '4008', '404', '405',
                                    '406', '407', '408', '5008', '504', '505', '508', '605', '607', '806', '807',
                                    'Bipper', 'Boxer', 'Expert', 'J5', 'J9', 'Partner', 'Pick Up', 'RCZ', 'Rifter',
                                    'Traveller'], 'Piaggio': ['Porter'],
                        'Plymouth': ['Acclaim', 'Breeze', 'Caravelle', 'Fury', 'Grand Voyager', 'Laser', 'Neon',
                                     'Prowler', 'Reliant', 'Sundance', 'Valiant', 'Voyager'],
                        'Polestar': ['1', '2', '3'],
                        'Pontiac': ['6000', 'Aztek', 'Bonneville', 'Catalina', 'Fiero', 'Firebird', 'G6', 'GTO',
                                    'Grand AM', 'Grand Prix', 'Laurentian', 'Montana', 'Solstice', 'Sunbird', 'Sunfire',
                                    'Sunrunner', 'Torrent', 'Trans Sport', 'Vibe'],
                        'Porsche': ['356', '718 Boxster', '718 Boxster S', '718 Cayman', '718 Cayman S', '911 Carrera',
                                    '911 Carrera 4', '911 Carrera 4 GTS', '911 Carrera 4S', '911 Carrera GTS',
                                    '911 Carrera S', '911 GT2', '911 GT2 RS', '911 GT3', '911 GT3 RS', '911 Speedster',
                                    '911 Targa 4', '911 Targa 4 GTS', '911 Targa 4S', '911 Turbo', '911 Turbo S', '924',
                                    '928', '944', '968', 'Boxster', 'Boxster S', 'Carrera GT', 'Cayenne',
                                    'Cayenne Coupe', 'Cayenne GTS', 'Cayenne S', 'Cayenne Turbo', 'Cayenne Turbo S',
                                    'Cayman', 'Cayman GT4', 'Cayman GTS', 'Cayman S', 'Macan', 'Macan GTS', 'Macan S',
                                    'Macan Turbo', 'Panamera', 'Panamera 4', 'Panamera 4S', 'Panamera GTS',
                                    'Panamera S', 'Panamera Turbo', 'Panamera Turbo S', 'Taycan',
                                    'Taycan Cross Turismo', 'Taycan Sport Turismo'], 'Premier': ['118NE', 'Padmini'],
                        'Proton': ['400 Series', 'Persona', 'Putra', 'Satria', 'Waja'], 'Puma': ['GTB', 'GTE'],
                        'Qoros': ['3', '5'], 'Qvale': ['Mangusta'], 'RAM': ['1500'],
                        'Ravon': ['Gentra', 'Matiz', 'Nexia', 'R2', 'R4'], 'Reliant': ['Robin', 'Scimitar'],
                        'Renaissance': ['Tropica Roadster'],
                        'Renault': ['11', '18', '19', '21', '25', '30', '4', '5', '9', 'Arkana', 'Austral', 'Avantime',
                                    'Captur', 'Caravelle', 'City K-ZE', 'Clio', 'Clio RS', 'Dokker', 'Dokker Stepway',
                                    'Dokker Van', 'Duster', 'Espace', 'Express', 'Fluence', 'Fuego', 'Grand Espace',
                                    'Grand Scenic', 'Kadjar', 'Kangoo', 'Kaptur', 'Koleos', 'Laguna', 'Latitude',
                                    'Lodgy', 'Logan', 'Logan Stepway', 'Lutecia', 'Master', 'Megane', 'Megane E-Tech',
                                    'Megane RS', 'Modus', 'Primaquatre', 'Rapid', 'Safrane', 'Sandero',
                                    'Sandero Stepway', 'Scenic', 'Symbol', 'Talisman', 'Trafic', 'Twingo', 'Twizy',
                                    'Vel SMTis', 'Vel Satis', 'Wind', 'ZOE'],
                        'Renault Samsung': ['QM3', 'QM5', 'QM6', 'SM3', 'SM3 Z.E', 'SM5', 'SM6', 'XM3'],
                        'Rezvani': ['Beast', 'Tank'], 'Rimac': ['C_Two', 'Concept_One'], 'Rinspeed': ['Chopster'],
                        'Rivian': ['R1S', 'R1T'], 'Rocar': ['TV41'], 'Roewe': ['Marvel R', 'RX5 Max', 'i5', 'iMAX 8'],
                        'Rolls-Royce': ['20/25', 'Corniche', 'Cullinan', 'Dawn', 'Ghost', 'Phantom', 'Silver Cloud',
                                        'Silver Seraph', 'Silver Shadow', 'Silver Spirit', 'Silver Spur',
                                        'Silver Wraith', 'Wraith'], 'Ronart': ['Lightning'],
                        'Rover': ['100', '200', '25', '400', '45', '600', '75', '800', 'MGF', 'Maestro', 'Mini MK',
                                  'Montego', 'SD1', 'Streetwise'],
                        'SEAT': ['Alhambra', 'Altea', 'Altea Freetrack', 'Altea XL', 'Arona', 'Arosa', 'Ateca',
                                 'Cordoba', 'Exeo', 'Ibiza', 'Ibiza Cupra', 'Ibiza FR', 'Inca', 'Leon', 'Leon Cupra',
                                 'Leon FR', 'Leon X-PERIENCE', 'Malaga', 'Marbella', 'Mii', 'Ronda', 'Tarraco', 'Terra',
                                 'Toledo'], 'SMA': ['C31', 'C32', 'C51', 'C52', 'C61', 'C81'], 'SOL': ['E20X'],
                        'SWM': ['G01', 'G01F', 'G01FF', 'G05', 'G05 Pro', 'Iron Man', 'Tiger', 'X2', 'X3', 'X7'],
                        'Saab': ['9-2X', '9-3', '9-4X', '9-5', '9-7X', '900', '9000', '95', '96', '99', 'Lancia 600'],
                        'Saic': ['Maxus EV30'], 'Saipa': ['Saina', 'Tiba'], 'Saleen': ['S7'], 'Santana': ['PS10'],
                        'Saturn': ['Astra', 'Aura', 'ION', 'LS', 'Outlook', 'SC', 'SL', 'SW', 'Sky', 'VUE'],
                        'Scion': ['FR-S', 'iA', 'tC', 'xA', 'xB', 'xD'], 'Seres': ['SF5'], 'Shuanghuan': ['Sceo'],
                        'Simca': ['1300/1500', '1307', 'Vedette'],
                        'Skoda': ['100', '105', 'Citigo', 'Fabia', 'Fabia RS', 'Fabia Scout', 'Favorit', 'Felicia',
                                  'Forman', 'Kamiq', 'Karoq', 'Kodiaq', 'Kodiaq RS', 'Octavia', 'Octavia (China)',
                                  'Octavia RS', 'Octavia Scout', 'Popular', 'Praktik', 'Rapid', 'Roomster',
                                  'Roomster Scout', 'Scala', 'Superb', 'Yeti'], 'Skywell': ['ET5', 'HT-i'],
                        'Smart': ['#1', 'Forfour', 'Fortwo', 'Roadster'], 'Sollers': ['Argo', 'Atlant'],
                        'Soueast': ['DX8S'], 'Spyker': ['C12', 'C8'],
                        'SsangYong': ['Actyon', 'Actyon Sports', 'Chairman', 'Istana', 'Korando', 'Korando Family',
                                      'Korando Sports', 'Korando Turismo', 'Kyron', 'Musso', 'Nomad', 'Rexton',
                                      'Rexton Sports', 'Rodius', 'Stavic', 'Tivoli', 'Tivoli XLV', 'Torres'],
                        'Steyr': ['120', '50'], 'Studebaker': ['Golden Hawk', 'President 8'],
                        'Subaru': ['Alcyone', 'Ascent', 'BRZ', 'Baja', 'Chiffon', 'Crosstrek', 'Dex', 'Dias', 'Domingo',
                                   'Exiga', 'Forester', 'Impreza', 'Impreza WRX STI', 'Justy', 'Legacy',
                                   'Legacy Lancaster', 'Leone', 'Levorg', 'Libero', 'Outback', 'Pleo', 'Pleo Plus',
                                   'R1', 'R2', 'Rex', 'SVX', 'Sambar', 'Solterra', 'Stella', 'Traviq', 'Trezia',
                                   'Tribeca', 'Vivio', 'WRX', 'WRX STI', 'XT', 'XV'],
                        'Suzuki': ['Aerio', 'Alto', 'Alto Lapin', 'Baleno', 'Cappuccino', 'Cara', 'Carry', 'Celerio',
                                   'Cervo', 'Chevrolet Cruze', 'Ciaz', 'Cultus', 'Cultus Wagon', 'DZire', 'Eeco',
                                   'Equator', 'Ertiga', 'Escudo', 'Esteem', 'Every', 'Every Landy', 'Forenza',
                                   'Grand Escudo', 'Grand Vitara', 'Hustler', 'Ignis', 'Jimny', 'Kei', 'Kizashi',
                                   'LJ 50', 'LJ 80', 'Landy', 'Liana', 'MR Wagon', 'Palette', 'Reno', 'S-Presso', 'SX4',
                                   'Samurai', 'Sidekick', 'Solio', 'Spacia', 'Splash', 'Swift', 'Swift (Japan)', 'Twin',
                                   'Verona', 'Vitara', 'Wagon R', 'Wagon R Solio', 'Wagon R Wide', 'Wagon R+', 'X-90',
                                   'XBee', 'XL7'],
                        'TVR': ['280', '350', '390', '400', '420', '450', 'Cerbera', 'Chimaera', 'Griffith', 'S-Series',
                                'Sagaris', 'Taimar', 'Tamora', 'Tasmin', 'Tuscan'], 'Talbot': ['Horizon'],
                        'Tank': ['300', '500'], 'Tata': ['Indica', 'Telcoline', 'Xenon'],
                        'Tatra': ['57', 'T603', 'T613', 'T700'], 'Tazzari': ['Zero'],
                        'Tesla': ['Model 3', 'Model S', 'Model X', 'Model Y', 'Roadster'], 'Think': ['City'],
                        'Tianma': ['Century', 'Dragon'], 'Tianye': ['Admiral'],
                        'Toyota': ['4Runner', 'Allex', 'Allion', 'Alphard', 'Altezza', 'Aqua', 'Aristo', 'Aurion',
                                   'Auris', 'Avalon', 'Avanza', 'Avensis', 'Avensis Verso', 'Aygo', 'Belta', 'Blade',
                                   'Blizzard', 'Brevis', 'C-HR', 'Caldina', 'Cami', 'Camry', 'Camry Gracia',
                                   'Camry Solara', 'Camry US Market', 'Carina', 'Carina E', 'Carina ED', 'Cavalier',
                                   'Celica', 'Celsior', 'Century', 'Chaser', 'Classic', 'Comfort', 'Coms', 'Corolla',
                                   'Corolla Axio', 'Corolla Ceres', 'Corolla Cross', 'Corolla Fielder', 'Corolla II',
                                   'Corolla Levin', 'Corolla Rumion', 'Corolla Runx', 'Corolla Spacio',
                                   'Corolla Sporty', 'Corolla Verso', 'Corona', 'Corona EXiV', 'Corona Premio', 'Corsa',
                                   'Cressida', 'Cresta', 'Crown', 'Crown Kluger', 'Crown Majesta', 'Curren', 'Cynos',
                                   'Duet', 'Echo', 'Esquire', 'Estima', 'Estima Lucida', 'FJ Cruiser', 'Fortuner',
                                   'Funcargo', 'GR86', 'GT86', 'Gaia', 'GranAce', 'Grand Hiace', 'Granvia', 'Harrier',
                                   'Hiace', 'Hiace Regius', 'Highlander', 'Hilux', 'Hilux Surf', 'Innova', 'Ipsum',
                                   'Isis', 'Ist', 'Izoa', 'Kluger', 'Land Cruiser', 'Land Cruiser Prado', 'Levin',
                                   'Lite Ace', 'Lite Ace Noah', 'MR-S', 'MR2', 'Mark II', 'Mark II Wagon Blit',
                                   'Mark II Wagon Qualis', 'Mark X', 'Mark X ZiO', 'MasterAce', 'Matrix',
                                   'Mega Cruiser', 'Mirai', 'Model F', 'Nadia', 'Noah', 'Opa', 'Paseo', 'Passo',
                                   'Passo Sette', 'Picnic', 'Pixis Epoch', 'Pixis Joy', 'Pixis Mega', 'Pixis Space',
                                   'Pixis Van', 'Platz', 'Porte', 'Premio', 'Previa', 'Prius', 'Prius Alpha', 'Prius C',
                                   'Prius PHV', 'Prius V', 'ProAce', 'Probox', 'Progres', 'Pronard', 'RAV4', 'Ractis',
                                   'Raize', 'Raum', 'Regius', 'Regius Ace', 'Roomy', 'Rush', 'SAI', 'Scepter',
                                   'Sequoia', 'Sera', 'Sienna', 'Sienta', 'Soarer', 'Soluna', 'Spade', 'Sparky',
                                   'Sprinter', 'Sprinter Carib', 'Sprinter Marino', 'Sprinter Trueno', 'Starlet',
                                   'Succeed', 'Supra', 'T100', 'Tacoma', 'Tank', 'Tercel', 'Touring Hiace', 'Town Ace',
                                   'Town Ace Noah', 'Tundra', 'Urban Cruiser', 'Vanguard', 'Vellfire', 'Veloz', 'Venza',
                                   'Verossa', 'Verso', 'Verso-S', 'Vios', 'Vista', 'Vista Ardeo', 'Vitz', 'Voltz',
                                   'Voxy', 'WiLL', 'WiLL Cypha', 'Windom', 'Wish', 'Yaris', 'Yaris Cross',
                                   'Yaris Verso', 'bB', 'bZ3', 'bZ4X', 'iQ'], 'Trabant': ['P601'],
                        'Tramontana': ['Tramontana'], 'Triumph': ['Spitfire', 'TR3'], 'Trumpchi': ['M8'],
                        'Ultima': ['GTR'], 'VGV': ['U70 Pro', 'U75 Plus'], 'Vauxhall': ['Astra', 'Cavalier', 'Viva'],
                        'Vector': ['M12', 'W8'], 'Venturi': ['210', '260', '300 Atlantique', '400 GT'],
                        'Volkswagen': ['181', 'Amarok', 'Arteon', 'Arteon R', 'Atlas', 'Atlas Cross Sport', 'Beetle',
                                       'Bora', 'Caddy', 'California', 'Caravelle', 'Corrado', 'Crafter', 'CrossPolo',
                                       'Derby', 'Eos', 'EuroVan', 'Fox', 'Gol', 'Golf', 'Golf Country', 'Golf GTI',
                                       'Golf Plus', 'Golf R', 'Golf R32', 'Golf Sportsvan', 'ID.3', 'ID.4',
                                       'ID.4 Crozz', 'ID.4 X', 'ID.5', 'ID.6 Crozz', 'ID.6 X', 'ID.Buzz', 'Jetta',
                                       'K70', 'Kaefer', 'LT', 'Lamando', 'Lavida', 'Lupo', 'Magotan', 'Multivan',
                                       'New Beetle', 'Passat', 'Passat (China)', 'Passat (North America)', 'Passat CC',
                                       'Phaeton', 'Phideon', 'Pointer', 'Polo', 'Polo GTI', 'Polo Plus', 'Routan',
                                       'Santana', 'Scirocco', 'Sharan', 'SpaceFox', 'T-Cross', 'T-Roc', 'T-Roc (China)',
                                       'T-Roc R', 'Tacqua', 'Talagon', 'Taos', 'Taro', 'Tavendor', 'Tayron', 'Tayron X',
                                       'Teramont', 'Teramont X', 'Tharu', 'Tiguan', 'Tiguan Allspace', 'Tiguan X',
                                       'Touareg', 'Touran', 'Touran Cross', 'Transporter', 'Type 1', 'Type 166',
                                       'Type 2', 'Type 4', 'Up', 'Vento', 'Viloran', 'e-Bora'],
                        'Volvo': ['140', '240', '260', '340', '360', '440', '460', '480', '66', '740', '760', '780',
                                  '850', '940', '960', 'C30', 'C40', 'C70', 'Laplander', 'P1800', 'PV444 / PV544',
                                  'S40', 'S60', 'S60 Cross Country', 'S70', 'S80', 'S90', 'V40', 'V40 Cross Country',
                                  'V50', 'V60', 'V60 Cross Country', 'V70', 'V90', 'V90 Cross Country', 'XC40', 'XC60',
                                  'XC70', 'XC90'], 'Vortex': ['Corda', 'Estina', 'Tingo'],
                        'Voyah': ['Dream', 'Free', 'Passion (Chasing Light)'],
                        'W Motors': ['Fenyr SuperSport', 'Lykan HyperSport'], 'Wanderer': ['W24', 'W40'],
                        'Wartburg': ['1.3', '353'], 'Weltmeister': ['EX5', 'W6'],
                        'Westfield': ['SEi & Sport', 'SEiGHT'], 'Wiesmann': ['GT', 'Roadster'],
                        'Willys': ['CJ', 'Jeepster', 'MB'], 'Wuling': ['Mini EV', 'Star Asta', 'Zhengtu (Fighting)'],
                        'XPeng': ['G3', 'P5', 'P7'], 'Xin Kai': ['Pickup X3', 'SR-V X3', 'SUV X3'],
                        'ZOTYE': ['Coupa', 'Nomad (RX6400)', 'T600', 'Z300'],
                        'ZX': ['Admiral', 'GrandTiger', 'Landmark'], 'Zastava': ['Florida'],
                        'Zeekr': ['001', '009', 'X'], 'Zenos': ['E10'], 'Zenvo': ['ST1'], 'Zhiji': ['L7'],
                        'Zibar': ['MK2'], 'Zuk': ['11', 'А06', 'А07'], 'Автокам': ['2160'], 'Апал': ['21541 (Сталкер)'],
                        'Богдан': ['2110', '2111', '2310', '2312'],
                        'ВАЗ (LADA)': ['1111 Ока', '1706 Челнок', '2101', '2102', '2103', '2104', '2105', '2106',
                                       '2107', '2108', '2109', '21099', '2110', '2111', '2112', '2113 Samara',
                                       '2114 Samara', '2115 Samara', '2120 Надежда', '2121 (4x4) Bronto',
                                       '2121 (4x4) Urban', '2121 (4x4) Рысь', '2121 (4x4) Фора', '2123', '2129',
                                       '2131 (4x4) Urban', '2131 (4x4) Рысь', '2302 Бизон', '2328', '2329',
                                       '4x4 (Нива)', 'El Lada', 'Granta', 'Granta Cross', 'Kalina', 'Kalina Cross',
                                       'Largus', 'Largus Cross', 'Niva', 'Niva Legend', 'Niva Legend Bronto',
                                       'Niva Off-road', 'Niva Travel', 'Priora', 'Revolution', 'Vesta', 'Vesta Cross',
                                       'XRAY', 'XRAY Cross'],
                        'ВИС': ['1705', '1706', '2345', '2346', '2347', '2349', '2950'],
                        'ГАЗ': ['12 ЗИМ', '13 Чайка', '14 Чайка', '21 Волга', '22 Волга', '23 Волга', '2308 Атаман',
                                '2330 Тигр', '24 Волга', '3102 Волга', '310221 Волга', '31029 Волга', '3105 Волга',
                                '3110 Волга', '31105 Волга', '3111 Волга', '64', '67', '69', 'M1', 'Volga Siber', 'А',
                                'ГАЗель 2705', 'ГАЗель 2747', 'ГАЗель 3221', 'ГАЗель 3302', 'ГАЗель 33023', 'ГАЗель NN',
                                'ГАЗель Next', 'М-20 Победа', 'М-72', 'Соболь 2217', 'Соболь 2310', 'Соболь 2752',
                                'Соболь NN'], 'ЕрАЗ': ['762'],
                        'ЗАЗ': ['1102 Таврия', '1103 Славута', '1105 Дана', '11055', '965 Запорожец', '966 Запорожец',
                                '968 Запорожец', 'Chance', 'Forza', 'Lanos', 'Sens', 'Vida'],
                        'ЗИЛ': ['110', '114', '117', '4104', '4105'], 'ЗиС': ['101', '110'],
                        'ИЖ': ['2125', '2126', '21261', '2715', '2717', 'Москвич-412'], 'Канонир': ['2317'],
                        'Комбат': ['Т98'], 'ЛуАЗ': ['1302', '967', '969'],
                        'Москвич': ['2136', '2137', '2138', '2140', '2141', '2335', '3', '3e', '400', '401', '402',
                                    '403', '407', '408', '410', '411', '412', '423', '424', '426', '427', '433', '6',
                                    'Иван Калита', 'Князь Владимир', 'Святогор', 'Юрий Долгорукий'], 'РАФ': ['2203'],
                        'Руссо-Балт': ['С-24'], 'СМЗ': ['С-1Л', 'С-3А', 'С-3Д'],
                        'ТагАЗ': ['Aquila', 'C10', 'C190', 'Hardy', 'Hyundai Accent', 'Hyundai Santa Fe Classic',
                                  'Master (LC100)', 'Road Partner', 'Tager', 'Vega', 'Vortex Corda', 'Vortex Estina',
                                  'Vortex Tingo', 'С30'],
                        'УАЗ': ['2206', '2360', '29891', '3151', '31512', '31514', '31519', '3153', '3159', '3160',
                                '3303', '3741', '3909', '39094', '39095', '3962', '450', '452 Буханка', '469', 'Hunter',
                                'Patriot', 'Pickup', 'Карго', 'Профи', 'Симбир']}


CAR_BRANDS_AND_MODELS_WITH_COMMA = []
for brand, models in CAR_MODELS_BY_BRANDS.items():
    for model in models:
        CAR_BRANDS_AND_MODELS_WITH_COMMA.append(f"{brand} {model}")


BRANDS_MODELS_CHOICES = [
    (name, name)
    for name in CAR_BRANDS_AND_MODELS_WITH_COMMA
]
