version: '3.9'

services:
  # ####################################################################################################################
  # Веб-сервисы (backend)
  # ####################################################################################################################
#  backend:
#    depends_on:
#      - postgres
#    ports:
#      - 8000:8000

  postgres:
    ports:
      - 5432:5432
