version: '3.9'

services:
  # ####################################################################################################################
  # Веб-сервисы (backend)
  # ####################################################################################################################

  postgres:
    ports:
      - 5433:5432

  mq:
    ports:
      - 5672:5672
      - 15672:15672
