# Generated by Django 4.2.1 on 2023-05-28 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('date_of_update', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('telegram_id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField()),
                ('username', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
