# Generated by Django 4.2.1 on 2023-05-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='need_to_notify',
            field=models.BooleanField(default=True, verbose_name='Уведомлять об объявлениях'),
        ),
    ]
